import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function Terms() {
  return (
    <div className="min-h-screen bg-slate-950">
      <Navbar />
      <div className="pt-32 pb-20 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-black mb-2">Terms of Service</h1>
          <p className="text-slate-500 text-sm mb-10">Last updated: February 18, 2026</p>

          <div className="space-y-8 text-slate-300 text-sm leading-relaxed">
            <section>
              <h2 className="text-lg font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using Blossom AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">2. Description of Service</h2>
              <p>Blossom AI provides AI-powered social media content analysis, viral format discovery, and content optimization tools. The Service analyzes publicly available content from platforms including Instagram and TikTok to provide insights and recommendations.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">3. Account Registration</h2>
              <p>You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">4. Subscriptions and Billing</h2>
              <p>Paid subscriptions are billed on a recurring basis. You may cancel your subscription at any time, which will take effect at the end of the current billing period. Refunds are handled in accordance with our billing provider's policies.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">5. Acceptable Use</h2>
              <p>You agree not to use the Service to:</p>
              <ul className="list-disc list-inside mt-2 space-y-1 text-slate-400">
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe on the intellectual property rights of others</li>
                <li>Harass, abuse, or harm other users</li>
                <li>Attempt to gain unauthorized access to the Service</li>
                <li>Use automated tools to scrape or extract data from the Service</li>
                <li>Resell or redistribute content or analysis from the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">6. Content and Intellectual Property</h2>
              <p>You retain ownership of content you upload for analysis. Analysis results and insights generated by the Service are provided for your personal use. The Service, including its algorithms, design, and branding, remains the intellectual property of Blossom AI.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">7. Limitation of Liability</h2>
              <p>The Service is provided "as is" without warranties of any kind. Blossom AI shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the Service in the preceding 12 months.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">8. Termination</h2>
              <p>We may suspend or terminate your account if you violate these terms. Upon termination, your right to use the Service ceases immediately. You may request deletion of your data by contacting support.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">9. Changes to Terms</h2>
              <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the revised terms. We will notify you of material changes via email or in-app notification.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">10. Contact</h2>
              <p>For questions about these terms, contact us at <a href="mailto:support@blossomapp.ai" className="text-pink-400 hover:text-pink-300">support@blossomapp.ai</a>.</p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}
